/**
 * OpenClaw Channel Session Sync - Minimal Version
 *
 * Retains only core utilities for session key management.
 * IM channel sync functionality removed for future adaptation.
 */

import type { CoworkStore } from '../coworkStore';

const JUSTDO_SESSION_PREFIX = 'justdo:';
export const DEFAULT_MANAGED_AGENT_ID = 'main';

export interface ManagedSessionKey {
  agentId: string | null;
  sessionId: string;
}

export function buildManagedSessionKey(
  sessionId: string,
  agentId = DEFAULT_MANAGED_AGENT_ID,
): string {
  const normalizedSessionId = sessionId.trim();
  const normalizedAgentId = agentId.trim() || DEFAULT_MANAGED_AGENT_ID;
  return `agent:${normalizedAgentId}:justdo:${normalizedSessionId}`;
}

export function parseManagedSessionKey(
  sessionKey: string | undefined | null,
): ManagedSessionKey | null {
  const raw = (sessionKey ?? '').trim();
  if (!raw) return null;

  if (raw.startsWith(JUSTDO_SESSION_PREFIX)) {
    const sessionId = raw.slice(JUSTDO_SESSION_PREFIX.length).trim();
    return sessionId ? { agentId: null, sessionId } : null;
  }

  if (!raw.startsWith('agent:')) {
    return null;
  }

  const parts = raw.split(':');
  if (parts.length < 4 || parts[0] !== 'agent' || parts[2] !== 'justdo') {
    return null;
  }

  const agentId = parts[1]?.trim();
  const sessionId = parts.slice(3).join(':').trim();
  if (!agentId || !sessionId) {
    return null;
  }

  return { agentId, sessionId };
}

export function isManagedSessionKey(sessionKey: string | undefined | null): boolean {
  return parseManagedSessionKey(sessionKey) !== null;
}

/**
 * Match cron-isolated session keys generated by the OpenClaw gateway.
 * Two formats:
 *   - "cron:{jobId}"                    — when agentId is not set on the job
 *   - "agent:{agentId}:cron:{jobId}"    — when agentId is set on the job
 */
const CRON_SESSION_KEY_RE = /^(?:agent:[^:]+:)?cron:[0-9a-f-]+$/i;

export function isCronSessionKey(sessionKey: string): boolean {
  return CRON_SESSION_KEY_RE.test(sessionKey);
}

/** Extract the jobId from a cron session key (either format). */
function extractCronJobId(sessionKey: string): string {
  const idx = sessionKey.lastIndexOf('cron:');
  return idx >= 0 ? sessionKey.slice(idx + 'cron:'.length) : sessionKey;
}

/** Match OpenClaw main agent session keys like "agent:main:main" or "agent:secondary:main". */
const MAIN_AGENT_SESSION_RE = /^agent:[^:]+:main$/;

/**
 * Extract the agentId from a gateway session key.
 * Key format: "agent:{agentId}:{channel}:..." → returns agentId.
 * Returns null for legacy keys or non-agent keys.
 */
export function extractAgentIdFromKey(sessionKey: string): string | null {
  if (!sessionKey.startsWith('agent:')) return null;
  const secondColon = sessionKey.indexOf(':', 6); // skip "agent:"
  if (secondColon <= 6) return null;
  return sessionKey.slice(6, secondColon);
}

/**
 * Minimal channel session sync for cron and main agent sessions only.
 * IM channel functionality removed.
 */
export interface ChannelSessionSyncDeps {
  coworkStore: CoworkStore;
  getDefaultCwd: () => string;
  /** Optional synchronous lookup: jobId → human-readable name (for cron session titles). */
  resolveJobName?: (jobId: string) => string | null;
}

export class OpenClawChannelSessionSync {
  private readonly coworkStore: CoworkStore;
  private readonly getDefaultCwd: () => string;
  private readonly resolveJobName: ((jobId: string) => string | null) | null;

  /** In-memory cache: openclawSessionKey → local sessionId. */
  private readonly syncedSessionKeys = new Map<string, string>();

  /** Keys that have been tried and are not recognized — avoids repeated log noise. */
  private readonly rejectedKeys = new Set<string>();

  constructor(deps: ChannelSessionSyncDeps) {
    this.coworkStore = deps.coworkStore;
    this.getDefaultCwd = deps.getDefaultCwd;
    this.resolveJobName = deps.resolveJobName ?? null;
  }

  /** Check whether a sessionKey belongs to a recognized main agent or cron session. */
  isChannelSessionKey(sessionKey: string): boolean {
    if (!sessionKey || isManagedSessionKey(sessionKey)) return false;
    if (MAIN_AGENT_SESSION_RE.test(sessionKey)) return true;
    if (isCronSessionKey(sessionKey)) return true;
    return false;
  }

  /**
   * Resolve or create a local Cowork session for the OpenClaw main agent session
   * (e.g. "agent:main:main"). This handles events that flow through the main session
   * rather than per-channel sessions.
   */
  resolveOrCreateMainAgentSession(sessionKey: string): string | null {
    if (isManagedSessionKey(sessionKey)) return null;
    if (!MAIN_AGENT_SESSION_RE.test(sessionKey)) return null;

    const cached = this.syncedSessionKeys.get(sessionKey);
    if (cached) {
      return cached;
    }

    const cwd = this.getDefaultCwd();
    console.log('[ChannelSessionSync] creating main agent session: key=', sessionKey, 'cwd=', cwd);
    const session = this.coworkStore.createSession('[OpenClaw]', cwd, 'local');
    console.log('[ChannelSessionSync] created main agent session:', session.id);

    this.syncedSessionKeys.set(sessionKey, session.id);
    return session.id;
  }

  /**
   * Resolve or create a local Cowork session for an OpenClaw cron-isolated session key.
   * Supported formats:
   *   - "cron:{jobId}"
   *   - "agent:{agentId}:cron:{jobId}"
   * Each cron job gets one persistent local session that is reused across runs,
   * keeping the full run history in a single conversation.
   */
  resolveOrCreateCronSession(sessionKey: string): string | null {
    if (!isCronSessionKey(sessionKey)) return null;

    const cached = this.syncedSessionKeys.get(sessionKey);
    if (cached) return cached;

    const jobId = extractCronJobId(sessionKey);
    // Prefer the human-readable job name for the session title; fall back to a short UUID prefix.
    const jobName = this.resolveJobName?.(jobId) ?? null;
    const cronLabel = 'Cron';
    const title = jobName
      ? `[${cronLabel}] ${jobName}`
      : `[${cronLabel}] ${jobId.length > 8 ? jobId.slice(0, 8) : jobId}`;
    const cwd = this.getDefaultCwd();
    console.log(
      '[ChannelSessionSync] creating cron session: key=',
      sessionKey,
      'title=',
      title,
      'cwd=',
      cwd,
    );
    const session = this.coworkStore.createSession(title, cwd, 'local');
    console.log('[ChannelSessionSync] created cron session:', session.id);

    this.syncedSessionKeys.set(sessionKey, session.id);
    return session.id;
  }

  /**
   * Resolve an existing cached session without creating a new one.
   * Returns the sessionId if the sessionKey has been previously synced.
   */
  resolveSession(sessionKey: string): string | null {
    return this.syncedSessionKeys.get(sessionKey) ?? null;
  }

  /**
   * Check if a session key matches current binding.
   * With IM channels removed, this always returns true for valid channel session keys.
   */
  isCurrentBindingKey(sessionKey: string): boolean {
    return this.isChannelSessionKey(sessionKey);
  }

  /**
   * Resolve or create a session for any recognized channel session key.
   * Tries main agent session first, then cron session.
   */
  resolveOrCreateSession(sessionKey: string): string | null {
    // Check cached first
    const cached = this.syncedSessionKeys.get(sessionKey);
    if (cached) return cached;

    // Try main agent session
    const mainSessionId = this.resolveOrCreateMainAgentSession(sessionKey);
    if (mainSessionId) return mainSessionId;

    // Try cron session
    return this.resolveOrCreateCronSession(sessionKey);
  }

  clearCache(): void {
    this.syncedSessionKeys.clear();
    this.rejectedKeys.clear();
  }

  /**
   * Purge in-memory cache entries for a deleted session so that
   * new messages with the same sessionKey can create a fresh session.
   */
  onSessionDeleted(sessionId: string): void {
    for (const [key, id] of this.syncedSessionKeys.entries()) {
      if (id === sessionId) {
        this.syncedSessionKeys.delete(key);
        // Also remove from rejectedKeys in case it was previously rejected,
        // so that re-discovery can succeed.
        this.rejectedKeys.delete(key);
      }
    }
  }
}
