general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
  user_header_mappings:
    - header_name: X-User-Account
      litellm_user_role: customer
