// Generated by scripts/browser/build-browser-extension-stream.cjs. Do not edit.

// src/shared/openclaw/agentEvent.ts
var TERMINAL_GUARD_OBSERVATION_KEY = "justdoTerminalGuardObservation";
function asRecord(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : null;
}
function readTerminalGuardObservation(data) {
  const value = asRecord(data[TERMINAL_GUARD_OBSERVATION_KEY]);
  const token = nonEmptyString(value?.token);
  const action = value?.action;
  if (!token || action !== "update" && action !== "commit" && action !== "rollback") {
    return null;
  }
  return { token, action };
}
function nonEmptyString(value) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

// src/shared/openclaw/messageDomain.ts
function normalizeMessageSessionKey(sessionKey) {
  const trimmed = sessionKey.trim();
  const managed = /^(?:agent:[^:]+:)?justdo:([^:]+)$/.exec(trimmed);
  return managed ? `justdo:${managed[1]}` : trimmed;
}
function messageSessionMatches(selected, event) {
  if (event.sessionId && selected.sessionId && event.sessionId !== selected.sessionId) return false;
  if (!event.sessionKey) return true;
  return normalizeMessageSessionKey(event.sessionKey) === normalizeMessageSessionKey(selected.sessionKey);
}
function classifyAgentEvent(params) {
  const { activeRun, event } = params;
  if (!messageSessionMatches(params.selected, event)) return "ignored-session";
  if (params.terminalRun) return "ignored-terminal";
  const hasSelectedSessionIdentity = Boolean(
    event.sessionKey || event.sessionId && params.selected.sessionId && event.sessionId === params.selected.sessionId
  );
  const canStartSelectedRun = !event.spawnedBy || hasSelectedSessionIdentity;
  if (!activeRun) return canStartSelectedRun ? "start-run" : "ignored-run";
  if (activeRun.runId !== event.runId) {
    if (activeRun.status !== "running") return canStartSelectedRun ? "start-run" : "ignored-run";
    return activeRun.runId.startsWith("justdo-") ? "bind-provisional-run" : "ignored-run";
  }
  if (activeRun.sessionId && event.sessionId && activeRun.sessionId !== event.sessionId) {
    return "ignored-session";
  }
  if (activeRun.lifecycleGeneration && event.lifecycleGeneration && activeRun.lifecycleGeneration !== event.lifecycleGeneration) {
    return "ignored-run";
  }
  if (event.agentSeq <= activeRun.lastAgentSeq) return "ignored-sequence";
  return "admitted";
}
function classifyChatEvent(params) {
  const { activeRun, event } = params;
  if (!messageSessionMatches(params.selected, event)) return "ignored-session";
  if (!activeRun) return event.state === "delta" && event.runId ? "start-run" : "ignored-run";
  if (event.runId && activeRun.runId !== event.runId) {
    return activeRun.runId.startsWith("justdo-") ? "bind-provisional-run" : "ignored-run";
  }
  if (event.sessionId && activeRun.sessionId && event.sessionId !== activeRun.sessionId) {
    return "ignored-session";
  }
  if (event.lifecycleGeneration && activeRun.lifecycleGeneration && event.lifecycleGeneration !== activeRun.lifecycleGeneration) {
    return "ignored-run";
  }
  return "admitted";
}
function normalizeToolTerminalStatus(phase, failed) {
  const normalized = typeof phase === "string" ? phase.trim().toLowerCase() : "";
  if (failed || normalized === "error" || normalized === "failed") return "failed";
  if (normalized === "cancel" || normalized === "cancelled" || normalized === "canceled" || normalized === "aborted") {
    return "cancelled";
  }
  if (normalized === "result" || normalized === "end" || normalized === "complete" || normalized === "completed" || normalized === "done" || normalized === "finish" || normalized === "finished") {
    return "completed";
  }
  return "running";
}
function asRecord2(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : null;
}
function firstString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.trim()) return value.trim();
  }
  return null;
}
function readableToolValue(value) {
  if (typeof value === "string") return value;
  if (Array.isArray(value)) {
    const parts = value.flatMap((entry) => {
      const record = asRecord2(entry);
      if (!record) return typeof entry === "string" ? [entry] : [];
      if (typeof record.text === "string") return [record.text];
      return record.content === void 0 ? [] : [readableToolValue(record.content)];
    });
    if (parts.length > 0) return parts.join("\n");
  }
  if (value === void 0 || value === null) return "";
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}
function meaningfulToolInput(value) {
  if (value === void 0 || value === null) return false;
  if (typeof value === "string") return Boolean(value.trim() && value.trim() !== "{}");
  if (Array.isArray(value)) return value.length > 0;
  return typeof value !== "object" || Object.keys(value).length > 0;
}
function coerceToolInput(value) {
  if (typeof value !== "string") return value;
  const trimmed = value.trim();
  if (!trimmed || !trimmed.startsWith("{") && !trimmed.startsWith("[")) return value;
  try {
    return JSON.parse(trimmed);
  } catch {
    return value;
  }
}
function outputIndicatesToolFailure(output) {
  if (!output) return false;
  const trimmed = output.trim();
  if (!trimmed) return false;
  if (/^tool not found\.?$/i.test(trimmed)) return true;
  if (trimmed.length > 2e4 || !trimmed.startsWith("{") || !trimmed.endsWith("}")) {
    return false;
  }
  try {
    const parsed = JSON.parse(trimmed);
    const record = asRecord2(parsed);
    if (!record) return false;
    if (record.isError === true || record.is_error === true) return true;
    if (typeof record.error === "string") return Boolean(record.error.trim());
    if (record.error === true || record.error && typeof record.error === "object") return true;
    const status = typeof record.status === "string" ? record.status.trim().toLowerCase() : "";
    return status === "error" || status === "failed" || status === "timeout";
  } catch {
    return false;
  }
}
function normalizeToolEvent(data, fallbackName = "tool") {
  const metadata = asRecord2(data.metadata);
  const toolCallId = firstString(
    data.toolCallId,
    data.tool_call_id,
    data.toolUseId,
    data.tool_use_id,
    data.callId,
    data.id,
    metadata?.toolCallId,
    metadata?.toolUseId
  );
  const name = firstString(data.name, data.toolName, data.tool_name, metadata?.toolName) ?? fallbackName;
  let input;
  for (const candidate of [
    data.toolInput,
    data.tool_input,
    data.arguments,
    data.args,
    data.input,
    metadata?.toolInput,
    metadata?.arguments,
    metadata?.args,
    metadata?.input,
    data.partialArgs
  ]) {
    const coerced = coerceToolInput(candidate);
    if (meaningfulToolInput(coerced)) {
      input = coerced;
      break;
    }
  }
  let output = null;
  for (const candidate of [
    data.result,
    data.partialResult,
    data.output,
    data.content,
    data.text,
    data.toolResult,
    data.summary,
    metadata?.toolResult
  ]) {
    if (candidate !== void 0 && candidate !== null) {
      output = readableToolValue(candidate);
      break;
    }
  }
  const rawError = data.error;
  const phase = typeof data.phase === "string" ? data.phase.trim().toLowerCase() : "";
  const rawStatus = typeof data.status === "string" ? data.status.trim().toLowerCase() : "";
  const failed = data.isError === true || data.is_error === true || rawError === true || typeof rawError === "string" && Boolean(rawError.trim()) || Boolean(rawError) && typeof rawError === "object" || rawStatus === "error" || rawStatus === "failed" || rawStatus === "timeout" || outputIndicatesToolFailure(output);
  const error = rawError === void 0 || rawError === null || rawError === false ? null : readableToolValue(rawError);
  return {
    toolCallId,
    name,
    ...input !== void 0 ? { input } : {},
    output,
    error,
    failed,
    status: normalizeToolTerminalStatus(phase, failed)
  };
}

// src/renderer/libs/openclaw-chat/model/chat-transcript-state.ts
var MAX_RECENT_RUNS = 24;
var RECENT_RUN_RETENTION_MS = 5 * 60 * 1e3;
function createChatTranscriptState(sessionKey = "", sessionId = null) {
  return {
    sessionKey,
    sessionId,
    persistedMessages: [],
    historySource: "optimistic",
    historyGeneration: 0,
    activeTurn: null,
    recentRuns: /* @__PURE__ */ new Map(),
    revision: 0
  };
}
function beginAssistantTurn(state, params, dependencies) {
  const turn = {
    id: dependencies.createId("turn"),
    runId: params.runId,
    sessionId: params.sessionId ?? state.sessionId,
    lifecycleGeneration: params.lifecycleGeneration ?? null,
    sessionKey: state.sessionKey,
    status: "running",
    lastAgentSeq: -1,
    activityEventSeqById: /* @__PURE__ */ new Map(),
    startedAt: params.startedAt ?? dependencies.now(),
    items: [],
    toolById: /* @__PURE__ */ new Map()
  };
  state.activeTurn = turn;
  state.revision += 1;
  return turn;
}
function bindAssistantTurnRunId(state, provisionalRunId, runId) {
  const turn = state.activeTurn;
  if (!turn || turn.runId !== provisionalRunId || !provisionalRunId.startsWith("justdo-")) {
    return false;
  }
  turn.runId = runId;
  for (const item of turn.items) item.runId = runId;
  state.revision += 1;
  return true;
}
function eventMatchesTranscriptSession(state, event) {
  return messageSessionMatches(state, event);
}
function pruneRecentRuns(state, now) {
  for (const [runId, run] of state.recentRuns) {
    if (run.expiresAt <= now) state.recentRuns.delete(runId);
  }
  while (state.recentRuns.size > MAX_RECENT_RUNS) {
    const oldest = state.recentRuns.keys().next().value;
    if (!oldest) break;
    state.recentRuns.delete(oldest);
  }
}

// src/renderer/libs/openclaw-chat/model/tool-lifecycle.ts
var SESSIONS_YIELD_TOOL_NAME = "sessions_yield";
function isSessionsYieldTool(name) {
  return name.trim().toLowerCase() === SESSIONS_YIELD_TOOL_NAME;
}
function hasToolResultPayload(tool) {
  return [tool.output, tool.error].some((value) => {
    if (value === void 0) return false;
    const normalized = value.trim();
    return normalized.length > 0 && normalized !== "[]";
  });
}
function inferSessionsYieldInput(name, output) {
  if (!isSessionsYieldTool(name) || !output?.trim()) return void 0;
  try {
    const parsed = JSON.parse(output);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return void 0;
    const message = parsed.message;
    return typeof message === "string" && message.trim() ? { message: message.trim() } : void 0;
  } catch {
    return void 0;
  }
}

// src/renderer/libs/openclaw-chat/model/agent-event-reducer.ts
function readPreambleText(data) {
  return data.kind === "preamble" && typeof data.progressText === "string" && data.progressText.trim() ? data.progressText : null;
}
function snapshotSegmentFirstSeq(event) {
  const value = event.data.progressSegmentFirstSeq;
  return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && value <= event.agentSeq ? value : null;
}
function segmentStartedAt(event) {
  const value = event.data.progressSegmentStartedAt;
  return snapshotSegmentFirstSeq(event) !== null && typeof value === "number" && Number.isFinite(value) && value > 0 && value <= event.timestamp ? value : event.timestamp;
}
function agentTailAtSequence(turn, seq) {
  let preceding;
  for (const item of turn.items) {
    if (item.firstSeq > seq) break;
    preceding = item;
  }
  return preceding;
}
function textOwnerForEvent(turn, event, backfill) {
  const firstSeq = snapshotSegmentFirstSeq(event);
  if (firstSeq !== null) {
    const type = event.stream === "thinking" ? "thinking" : "content";
    const owned = turn.items.find((item) => item.type === type && item.firstSeq === firstSeq);
    if (owned) return owned;
    const text = stringValue(event.data.thinking) ?? stringValue(event.data.text);
    if (!text?.trim()) return void 0;
    const startedAt = segmentStartedAt(event);
    const matches = turn.items.filter((item, index) => {
      if (item.type !== type || !item.recoveredSnapshotText || item.type === "content" && item.preambleItemId !== void 0)
        return false;
      if (turn.activityEventSeqById?.has(`segment:${JSON.stringify([event.stream, item.firstSeq])}`))
        return false;
      const nextTool = turn.items.slice(index + 1).find((candidate) => candidate.type === "tool");
      const previousTool = turn.items.slice(0, index).reverse().find((candidate) => candidate.type === "tool");
      if (!nextTool || nextTool.agentSequenceUnconfirmed === true && nextTool.historyCompletedAt !== void 0 && startedAt > nextTool.historyCompletedAt || nextTool.agentSequenceUnconfirmed !== true && nextTool.agentSequencePending === true && startedAt > nextTool.startedAt || !nextTool.agentSequencePending && !nextTool.agentSequenceUnconfirmed && firstSeq >= nextTool.firstSeq || previousTool && !previousTool.agentSequencePending && !previousTool.agentSequenceUnconfirmed && firstSeq <= previousTool.firstSeq)
        return false;
      return item.recoveredSnapshotText.startsWith(text.trim());
    });
    if (matches.length !== 1) return void 0;
    matches[0].firstSeq = firstSeq;
    matches[0].startedAt = Math.min(matches[0].startedAt, startedAt);
    return matches[0];
  }
  const tail = backfill ? agentTailAtSequence(turn, event.agentSeq) : activeAgentTail(turn);
  return tail?.type === "content" && tail.preambleItemId !== void 0 ? void 0 : tail;
}
function finishTextBeforeKnownBoundaries(turn) {
  for (let index = 0; index < turn.items.length - 1; index += 1) {
    const item = turn.items[index];
    const next = turn.items[index + 1];
    if (item.type === "thinking" && item.status === "running") item.status = "completed";
    if (item.type === "content") {
      if (item.status === "streaming") item.status = "completed";
      if (next.type === "tool") item.followingToolCallId = next.toolCallId;
    }
  }
}
function preservesRecoveredText(turn, item, event, text) {
  if (!item.recoveredSnapshotText?.startsWith(text.trim())) return false;
  const nextTool = turn.items.slice(turn.items.indexOf(item) + 1).find((candidate) => candidate.type === "tool");
  return Boolean(nextTool && event.timestamp > 0 && event.timestamp <= nextTool.startedAt);
}
function stringValue(value) {
  return typeof value === "string" ? value : null;
}
function activeAgentTailIndex(turn) {
  const pendingToolIndex = turn.items.findIndex(
    (item) => item.type === "tool" && item.agentSequencePending === true
  );
  return (pendingToolIndex < 0 ? turn.items.length : pendingToolIndex) - 1;
}
function pendingRecoveredTool(turn) {
  return turn.items.find(
    (item) => item.type === "tool" && item.agentSequencePending === true
  );
}
function thinkingBeforeTool(turn, tool) {
  const toolIndex = turn.items.indexOf(tool);
  if (toolIndex < 0) return void 0;
  for (let index = toolIndex - 1; index >= 0; index -= 1) {
    const item = turn.items[index];
    if (item.type === "tool") break;
    if (item.type === "thinking") return item;
  }
  return void 0;
}
function contentBeforeTool(turn, tool) {
  const toolIndex = turn.items.indexOf(tool);
  if (toolIndex < 0) return void 0;
  for (let index = toolIndex - 1; index >= 0; index -= 1) {
    const item = turn.items[index];
    if (item.type === "tool") break;
    if (item.type === "content") return item;
  }
  return void 0;
}
function activeAgentTail(turn) {
  return turn.items[activeAgentTailIndex(turn)];
}
function appendAgentItem(turn, item) {
  const pendingToolIndex = turn.items.findIndex(
    (candidate) => candidate.type === "tool" && candidate.agentSequencePending === true
  );
  if (pendingToolIndex < 0) turn.items.push(item);
  else turn.items.splice(pendingToolIndex, 0, item);
}
function itemToolCallId(data) {
  for (const value of [
    data.toolCallId,
    data.tool_call_id,
    data.toolUseId,
    data.tool_use_id,
    data.callId
  ]) {
    const explicit = stringValue(value)?.trim();
    if (explicit) return explicit;
  }
  const itemId = stringValue(data.itemId)?.trim() ?? "";
  const match = /^(?:tool|command|patch):(.+)$/i.exec(itemId);
  return match?.[1]?.trim() || null;
}
function eventItemId(data) {
  return stringValue(data.itemId)?.trim() || stringValue(data.id)?.trim() || null;
}
function activityEventIdentity(event) {
  const segmentFirstSeq = snapshotSegmentFirstSeq(event);
  if (segmentFirstSeq !== null && (event.stream === "thinking" || event.stream === "assistant")) {
    return `segment:${JSON.stringify([event.stream, segmentFirstSeq])}`;
  }
  if (event.stream === "tool") {
    const toolCallId = itemToolCallId(event.data);
    if (toolCallId) return `tool:${JSON.stringify(toolCallId)}`;
  }
  if (event.stream === "item") {
    const kind = stringValue(event.data.kind)?.trim() || "item";
    const itemId2 = eventItemId(event.data) ?? "latest";
    return `item:${JSON.stringify([kind, itemId2])}`;
  }
  const itemId = eventItemId(event.data);
  return itemId ? `stream:${JSON.stringify([event.stream, itemId])}` : `stream:${JSON.stringify(event.stream)}`;
}
function toolTerminalIdentity(ownerIdentity) {
  return `${ownerIdentity}:result`;
}
function isTerminalToolEvent(event) {
  if (event.stream !== "tool") return false;
  const phase = stringValue(event.data.phase)?.trim().toLowerCase();
  return phase === "result" || phase === "error" || phase === "failed";
}
function fillsMissingToolInput(turn, event) {
  if (event.stream !== "tool" || event.deliveryEvent !== "session.tool") return false;
  const normalized = normalizeToolEvent(event.data);
  const existing = normalized.toolCallId ? turn.toolById.get(normalized.toolCallId) : void 0;
  return existing !== void 0 && existing.status !== "running" && existing.input === void 0 && normalized.input !== void 0 && normalized.input !== null;
}
function acceptsBackfillSequence(turn, event) {
  if (fillsMissingToolInput(turn, event)) return true;
  const ownerIdentity = activityEventIdentity(event);
  const sequences = turn.activityEventSeqById;
  if (event.stream === "tool" && !isTerminalToolEvent(event)) {
    const terminalSeq = sequences?.get(toolTerminalIdentity(ownerIdentity));
    if (terminalSeq !== void 0 && event.agentSeq <= terminalSeq) return false;
  }
  const previous = sequences?.get(ownerIdentity);
  return previous === void 0 || event.agentSeq > previous;
}
function recordActivitySequence(turn, event) {
  const ownerIdentity = activityEventIdentity(event);
  const sequences = turn.activityEventSeqById ??= /* @__PURE__ */ new Map();
  sequences.set(ownerIdentity, Math.max(sequences.get(ownerIdentity) ?? -1, event.agentSeq));
  if (isTerminalToolEvent(event)) {
    const terminalIdentity = toolTerminalIdentity(ownerIdentity);
    sequences.set(
      terminalIdentity,
      Math.max(sequences.get(terminalIdentity) ?? -1, event.agentSeq)
    );
  }
}
function insertAgentItemBySequence(turn, item) {
  const insertionIndex = turn.items.findIndex(
    (candidate) => candidate.type === "tool" && candidate.agentSequencePending === true ? candidate.agentSequenceUnconfirmed === true || item.startedAt > 0 && item.startedAt <= candidate.startedAt : candidate.type === "tool" && candidate.agentSequenceUnconfirmed === true && candidate.historyCompletedAt !== void 0 && item.startedAt > 0 ? item.startedAt <= candidate.historyCompletedAt : candidate.firstSeq > item.firstSeq
  );
  if (insertionIndex < 0) turn.items.push(item);
  else turn.items.splice(insertionIndex, 0, item);
}
function confirmRecoveredToolSequence(turn, tool, seq, timestamp, source = "agent") {
  if (tool.agentSequencePending !== true && tool.agentSequenceUnconfirmed !== true && (source === "history" || seq >= tool.firstSeq))
    return false;
  let toolIndex = turn.items.indexOf(tool);
  delete tool.agentSequencePending;
  if (source === "history") {
    tool.agentSequenceUnconfirmed = true;
  } else {
    tool.firstSeq = seq;
    delete tool.agentSequenceUnconfirmed;
    delete tool.historyCompletedAt;
    if (toolIndex >= 0) {
      turn.items.splice(toolIndex, 1);
      insertAgentItemBySequence(turn, tool);
      toolIndex = turn.items.indexOf(tool);
    }
  }
  const previous = toolIndex > 0 ? turn.items[toolIndex - 1] : void 0;
  for (const item of turn.items) {
    if (item.type === "content" && item !== previous && item.followingToolCallId === tool.toolCallId) {
      delete item.followingToolCallId;
    }
  }
  if (previous?.type === "thinking" && previous.status === "running") {
    previous.status = "completed";
    previous.lastSeq = Math.max(previous.lastSeq, seq);
    previous.updatedAt = Math.max(previous.updatedAt, timestamp);
  } else if (previous?.type === "content") {
    if (previous.status === "streaming") previous.status = "completed";
    previous.followingToolCallId = tool.toolCallId;
    previous.lastSeq = Math.max(previous.lastSeq, seq);
    previous.updatedAt = Math.max(previous.updatedAt, timestamp);
  }
  return true;
}
function hydrateToolPrecedingThinking(turn, tool, text, authoritative, seq, timestamp, dependencies) {
  if (!authoritative && tool.agentSequencePending !== true) return false;
  const normalizedText = text?.trim() || null;
  const authoritativeText = authoritative ? normalizedText : null;
  const existing = thinkingBeforeTool(turn, tool);
  if (existing) {
    let changed = false;
    if (normalizedText && existing.text !== normalizedText) {
      existing.text = authoritative ? normalizedText : updateSnapshot(existing.text, normalizedText, false);
      changed = true;
    }
    if (authoritativeText && existing.recoveredSnapshotText === void 0 && existing.text === authoritativeText && changed) {
      existing.recoveredSnapshotText = authoritativeText;
    }
    if (existing.status === "running") {
      existing.status = "completed";
      changed = true;
    }
    existing.lastSeq = Math.max(existing.lastSeq, seq);
    existing.updatedAt = Math.max(existing.updatedAt, timestamp);
    return changed;
  }
  if (!normalizedText) return false;
  const toolIndex = turn.items.indexOf(tool);
  if (toolIndex < 0) return false;
  let insertionIndex = toolIndex;
  while (insertionIndex > 0 && turn.items[insertionIndex - 1].type !== "tool") {
    insertionIndex -= 1;
  }
  turn.items.splice(insertionIndex, 0, {
    id: dependencies.createId("history-thinking"),
    runId: turn.runId,
    firstSeq: seq,
    lastSeq: seq,
    startedAt: Math.min(timestamp, tool.startedAt),
    updatedAt: timestamp,
    type: "thinking",
    status: "completed",
    text: normalizedText,
    ...authoritativeText ? { recoveredSnapshotText: authoritativeText } : {}
  });
  return true;
}
function hydrateToolPrecedingContent(turn, tool, text, authoritative, seq, timestamp, dependencies) {
  if (!authoritative && tool.agentSequencePending !== true) return false;
  const normalizedText = text?.trim() || null;
  const authoritativeText = authoritative ? normalizedText : null;
  const existing = contentBeforeTool(turn, tool);
  if (existing) {
    let changed = false;
    if (normalizedText && existing.text !== normalizedText) {
      existing.text = authoritative ? normalizedText : updateSnapshot(existing.text, normalizedText, false);
      changed = true;
    }
    if (authoritativeText && existing.recoveredSnapshotText === void 0 && existing.text === authoritativeText && changed) {
      existing.recoveredSnapshotText = authoritativeText;
    }
    if (existing.status === "streaming") {
      existing.status = "completed";
      changed = true;
    }
    if (existing.followingToolCallId !== tool.toolCallId) {
      existing.followingToolCallId = tool.toolCallId;
      changed = true;
    }
    existing.lastSeq = Math.max(existing.lastSeq, seq);
    existing.updatedAt = Math.max(existing.updatedAt, timestamp);
    return changed;
  }
  if (!normalizedText) return false;
  const toolIndex = turn.items.indexOf(tool);
  if (toolIndex < 0) return false;
  turn.items.splice(toolIndex, 0, {
    id: dependencies.createId("history-content"),
    runId: turn.runId,
    firstSeq: seq,
    lastSeq: seq,
    startedAt: Math.min(timestamp, tool.startedAt),
    updatedAt: timestamp,
    type: "content",
    status: "completed",
    text: normalizedText,
    sourceMode: "snapshot",
    followingToolCallId: tool.toolCallId,
    ...authoritativeText ? { recoveredSnapshotText: authoritativeText } : {}
  });
  return true;
}
function completeRunningThinking(turn, seq, now) {
  const tail = activeAgentTail(turn);
  if (tail?.type === "thinking" && tail.status === "running") {
    tail.status = "completed";
    tail.lastSeq = seq;
    tail.updatedAt = now;
  }
}
function completeStreamingContent(turn, seq, now) {
  const tail = activeAgentTail(turn);
  if (tail?.type === "content" && tail.status === "streaming") {
    tail.status = "completed";
    tail.lastSeq = seq;
    tail.updatedAt = now;
  }
}
function createBase(turn, event, dependencies, prefix) {
  return {
    id: dependencies.createId(prefix),
    runId: turn.runId,
    firstSeq: snapshotSegmentFirstSeq(event) ?? event.agentSeq,
    lastSeq: event.agentSeq,
    startedAt: segmentStartedAt(event),
    updatedAt: event.timestamp
  };
}
function updateSnapshot(previous, next, replace) {
  if (replace || !previous) return next;
  if (next.startsWith(previous) || previous.startsWith(next)) {
    return next.length >= previous.length ? next : previous;
  }
  return next;
}
function snapshotDistanceFromCurrent(candidate, current) {
  const normalizedCandidate = candidate.trimStart();
  const normalizedCurrent = current.trimStart();
  if (normalizedCandidate === normalizedCurrent) return 0;
  if (normalizedCandidate.startsWith(normalizedCurrent)) {
    return normalizedCandidate.length - normalizedCurrent.length;
  }
  if (normalizedCurrent.startsWith(normalizedCandidate)) {
    return normalizedCurrent.length - normalizedCandidate.length;
  }
  return Number.POSITIVE_INFINITY;
}
function stripCompletedContentSegments(turn, snapshot) {
  let text = snapshot;
  for (const item of turn.items) {
    if (item.type !== "content" || item.status === "streaming") continue;
    const committed = item.text.trim();
    if (!committed) continue;
    const trimmed = text.trimStart();
    if (trimmed.startsWith(committed)) {
      text = trimmed.slice(committed.length).trimStart();
    }
  }
  const tail = activeAgentTail(turn);
  if (tail?.type === "content") {
    const rawDistance = snapshotDistanceFromCurrent(snapshot, tail.text);
    const strippedDistance = snapshotDistanceFromCurrent(text, tail.text);
    if (rawDistance <= strippedDistance) return snapshot;
  }
  return text;
}
function reduceThinking(turn, event, dependencies, backfill = false) {
  const snapshot = stringValue(event.data.thinking) ?? stringValue(event.data.text);
  const delta = stringValue(event.data.delta);
  const isDelta = delta !== null && (snapshot === null || !snapshot.trim());
  const text = isDelta ? delta : snapshot ?? delta;
  if (text === null) return;
  if (!text.trim()) {
    const tail2 = textOwnerForEvent(turn, event, backfill);
    if (isDelta && tail2?.type === "thinking" && tail2.status === "running" && tail2.text) {
      tail2.text += text;
      tail2.lastSeq = event.agentSeq;
      tail2.updatedAt = event.timestamp;
    }
    return;
  }
  const normalizedText = text.trim();
  const recovered = snapshotSegmentFirstSeq(event) === null ? turn.items.find(
    (item2) => item2.type === "thinking" && typeof item2.recoveredSnapshotText === "string" && item2.recoveredSnapshotText.includes(normalizedText)
  ) : void 0;
  if (recovered) {
    recovered.lastSeq = Math.max(recovered.lastSeq, event.agentSeq);
    recovered.updatedAt = Math.max(recovered.updatedAt, event.timestamp);
    if (recovered.recoveredSnapshotText === normalizedText) {
      delete recovered.recoveredSnapshotText;
    }
    return;
  }
  const recoveredTool = snapshotSegmentFirstSeq(event) === null ? pendingRecoveredTool(turn) : void 0;
  if (recoveredTool) {
    const existing = thinkingBeforeTool(turn, recoveredTool);
    if (existing) {
      const authoritativeText = existing.recoveredSnapshotText;
      if (authoritativeText) {
        existing.text = authoritativeText;
      } else {
        existing.text = isDelta ? `${existing.text}${text}` : updateSnapshot(existing.text, text, event.data.replace === true);
      }
      existing.status = "completed";
      existing.lastSeq = event.agentSeq;
      existing.updatedAt = event.timestamp;
      return;
    }
    hydrateToolPrecedingThinking(
      turn,
      recoveredTool,
      text,
      false,
      event.agentSeq,
      event.timestamp,
      dependencies
    );
    return;
  }
  const tail = textOwnerForEvent(turn, event, backfill);
  if (!backfill && tail?.type !== "thinking")
    completeStreamingContent(turn, event.agentSeq, event.timestamp);
  if (tail?.type === "thinking" && (tail.status === "running" || backfill || snapshotSegmentFirstSeq(event) !== null)) {
    tail.text = isDelta ? `${tail.text}${text}` : updateSnapshot(
      tail.text,
      text,
      event.data.replace === true && !preservesRecoveredText(turn, tail, event, text)
    );
    if (!isDelta && tail.recoveredSnapshotText === text.trim()) delete tail.recoveredSnapshotText;
    tail.lastSeq = event.agentSeq;
    tail.updatedAt = event.timestamp;
    return;
  }
  const item = {
    ...createBase(turn, event, dependencies, "thinking"),
    type: "thinking",
    status: backfill && turn.items.some((candidate) => candidate.firstSeq > event.agentSeq) ? "completed" : "running",
    text
  };
  if (backfill || snapshotSegmentFirstSeq(event) !== null) insertAgentItemBySequence(turn, item);
  else appendAgentItem(turn, item);
}
function reducePreamble(turn, event, dependencies) {
  const text = readPreambleText(event.data);
  if (!text) return;
  const itemId = eventItemId(event.data);
  const nativeFirstSeq = snapshotSegmentFirstSeq(event);
  const existing = turn.items.find(
    (item) => item.type === "content" && item.preambleItemId !== void 0 && (itemId !== null ? item.preambleItemId === itemId : nativeFirstSeq !== null ? item.firstSeq === nativeFirstSeq : item.preambleItemId === "" && item.status === "streaming")
  );
  const content = reduceContent(
    turn,
    {
      ...event,
      stream: "assistant",
      data: {
        text,
        replace: true,
        progressSegmentFirstSeq: existing?.firstSeq ?? nativeFirstSeq ?? event.agentSeq,
        progressSegmentStartedAt: typeof event.data.progressSegmentStartedAt === "number" ? event.data.progressSegmentStartedAt : existing?.startedAt ?? event.timestamp
      }
    },
    dependencies,
    true
  );
  if (!content) return;
  content.preambleItemId = itemId ?? "";
  if (event.data.phase === "end") content.status = "completed";
  finishTextBeforeKnownBoundaries(turn);
}
function reduceContent(turn, event, dependencies, backfill = false) {
  const snapshot = stringValue(event.data.text);
  const delta = stringValue(event.data.delta);
  const isDelta = delta !== null && (snapshot === null || !snapshot.trim());
  const text = isDelta ? delta : snapshot ?? delta;
  if (text === null) return null;
  if (!text.trim()) {
    const tail2 = textOwnerForEvent(turn, event, backfill);
    if (isDelta && tail2?.type === "content" && tail2.status === "streaming" && tail2.text) {
      tail2.text += text;
      tail2.sourceMode = "delta";
      tail2.lastSeq = event.agentSeq;
      tail2.updatedAt = event.timestamp;
      return tail2;
    }
    return null;
  }
  if (snapshotSegmentFirstSeq(event) === null && snapshot !== null && snapshot.trim()) {
    const normalizedSnapshot = snapshot.trim();
    const recovered = turn.items.find(
      (item2) => item2.type === "content" && item2.preambleItemId === void 0 && typeof item2.recoveredSnapshotText === "string" && item2.recoveredSnapshotText.startsWith(normalizedSnapshot)
    );
    if (recovered) {
      recovered.lastSeq = Math.max(recovered.lastSeq, event.agentSeq);
      recovered.updatedAt = Math.max(recovered.updatedAt, event.timestamp);
      if (recovered.recoveredSnapshotText === normalizedSnapshot) {
        delete recovered.recoveredSnapshotText;
      }
      return recovered;
    }
  }
  const recoveredTool = snapshotSegmentFirstSeq(event) === null ? pendingRecoveredTool(turn) : void 0;
  if (recoveredTool) {
    const existing = contentBeforeTool(turn, recoveredTool);
    if (existing) {
      const authoritativeText = existing.recoveredSnapshotText;
      if (authoritativeText) {
        existing.text = authoritativeText;
      } else {
        existing.text = isDelta ? `${existing.text}${text}` : updateSnapshot(existing.text, text, event.data.replace === true);
      }
      existing.status = "completed";
      existing.followingToolCallId = recoveredTool.toolCallId;
      existing.lastSeq = event.agentSeq;
      existing.updatedAt = event.timestamp;
      return existing;
    }
    const hydrated = hydrateToolPrecedingContent(
      turn,
      recoveredTool,
      text,
      false,
      event.agentSeq,
      event.timestamp,
      dependencies
    );
    return hydrated ? contentBeforeTool(turn, recoveredTool) ?? null : null;
  }
  const tail = textOwnerForEvent(turn, event, backfill);
  if (!backfill && tail?.type !== "content")
    completeRunningThinking(turn, event.agentSeq, event.timestamp);
  const replace = event.data.replace === true;
  if (tail?.type === "content" && (tail.status === "streaming" || backfill || snapshotSegmentFirstSeq(event) !== null)) {
    if (isDelta && !replace) {
      tail.text += text;
      tail.sourceMode = "delta";
    } else {
      tail.text = updateSnapshot(
        tail.text,
        text,
        replace && !preservesRecoveredText(turn, tail, event, text)
      );
      tail.sourceMode = replace ? "replaceable" : "snapshot";
      if (tail.recoveredSnapshotText === text.trim()) delete tail.recoveredSnapshotText;
    }
    tail.lastSeq = event.agentSeq;
    tail.updatedAt = event.timestamp;
    return tail;
  }
  const item = {
    ...createBase(turn, event, dependencies, "content"),
    type: "content",
    status: backfill && turn.items.some((candidate) => candidate.firstSeq > event.agentSeq) ? "completed" : "streaming",
    text,
    sourceMode: replace ? "replaceable" : isDelta ? "delta" : "snapshot"
  };
  if (backfill || snapshotSegmentFirstSeq(event) !== null) {
    const followingItem = turn.items.find((candidate) => candidate.firstSeq > event.agentSeq);
    if (followingItem?.type === "tool") item.followingToolCallId = followingItem.toolCallId;
    insertAgentItemBySequence(turn, item);
  } else {
    appendAgentItem(turn, item);
  }
  return item;
}
function applyTerminalGuardObservationDecision(turn, observation) {
  if (observation.action === "update") return;
  for (let index = turn.items.length - 1; index >= 0; index -= 1) {
    const item = turn.items[index];
    if (item.type !== "content" || item.terminalGuardObservationToken !== observation.token) {
      continue;
    }
    if (observation.action === "rollback") turn.items.splice(index, 1);
    else delete item.terminalGuardObservationToken;
  }
}
function reduceTool(turn, event, dependencies, backfill = false) {
  const normalized = normalizeToolEvent(event.data);
  const toolCallId = normalized.toolCallId;
  if (!toolCallId) return false;
  const existing = turn.toolById.get(toolCallId);
  const resolved = normalizeToolEvent(event.data, existing?.name ?? "tool");
  const resolvedInput = resolved.input ?? existing?.input ?? inferSessionsYieldInput(resolved.name, resolved.output ?? existing?.output);
  const sessionsYieldHasPayload = hasToolResultPayload({
    output: resolved.output ?? void 0,
    error: resolved.error ?? void 0
  }) || existing !== void 0 && hasToolResultPayload(existing);
  const outputlessSessionsYieldResult = isSessionsYieldTool(resolved.name) && resolved.status === "completed" && !sessionsYieldHasPayload;
  const status = outputlessSessionsYieldResult ? "running" : resolved.status;
  if (existing) {
    if (backfill && existing.agentSequencePending !== true && existing.lastSeq >= event.agentSeq) {
      if (fillsMissingToolInput(turn, event)) {
        existing.input = resolved.input;
        if (existing.name === "tool") existing.name = resolved.name;
        return true;
      }
      return false;
    }
    const preserveExistingTerminal = backfill && existing.status !== "running";
    confirmRecoveredToolSequence(turn, existing, event.agentSeq, event.timestamp);
    if (!preserveExistingTerminal || existing.name === "tool") existing.name = resolved.name;
    if (resolvedInput !== void 0 && resolvedInput !== null && (!preserveExistingTerminal || existing.input === void 0)) {
      existing.input = resolvedInput;
    }
    if (resolved.output !== null && !outputlessSessionsYieldResult && (!preserveExistingTerminal || existing.output === void 0)) {
      existing.output = resolved.output;
    }
    if (resolved.error !== null && !outputlessSessionsYieldResult && (!preserveExistingTerminal || existing.error === void 0)) {
      existing.error = resolved.error;
    }
    if (!preserveExistingTerminal && (existing.status === "running" || status !== "running")) {
      existing.status = status;
    }
    existing.lastSeq = Math.max(existing.lastSeq, event.agentSeq);
    existing.updatedAt = Math.max(existing.updatedAt, event.timestamp);
    return true;
  }
  if (!backfill) {
    completeRunningThinking(turn, event.agentSeq, event.timestamp);
    const previous = activeAgentTail(turn);
    if (previous?.type === "content" && previous.status === "streaming") {
      previous.status = "completed";
      previous.followingToolCallId = toolCallId;
      previous.lastSeq = event.agentSeq;
      previous.updatedAt = event.timestamp;
    }
  }
  const item = {
    ...createBase(turn, event, dependencies, "tool"),
    type: "tool",
    status,
    toolCallId,
    name: resolved.name,
    ...resolvedInput !== void 0 && resolvedInput !== null ? { input: resolvedInput } : {},
    ...normalized.output !== null && !outputlessSessionsYieldResult ? { output: normalized.output } : {},
    ...normalized.error !== null && !outputlessSessionsYieldResult ? { error: normalized.error } : {}
  };
  if (backfill) insertAgentItemBySequence(turn, item);
  else appendAgentItem(turn, item);
  turn.toolById.set(toolCallId, item);
  return true;
}
function admitTurn(state, event, dependencies, allowSequenceBackfill = false) {
  pruneRecentRuns(state, dependencies.now());
  const tombstone = state.recentRuns.get(event.runId);
  const active = state.activeTurn;
  const admission = classifyAgentEvent({
    selected: state,
    activeRun: active,
    event,
    terminalRun: Boolean(tombstone?.terminalStatus)
  });
  if (admission === "ignored-session" || admission === "ignored-run" || admission === "ignored-sequence" && !allowSequenceBackfill || admission === "ignored-terminal") {
    return null;
  }
  if (admission === "bind-provisional-run" && active) {
    bindAssistantTurnRunId(state, active.runId, event.runId);
  } else if (admission === "start-run") {
    return beginAssistantTurn(
      state,
      {
        runId: event.runId,
        sessionId: event.sessionId,
        lifecycleGeneration: event.lifecycleGeneration,
        startedAt: event.timestamp
      },
      dependencies
    );
  }
  const admitted = state.activeTurn;
  if (admitted && !admitted.sessionId && event.sessionId) admitted.sessionId = event.sessionId;
  if (admitted && !admitted.lifecycleGeneration && event.lifecycleGeneration) {
    admitted.lifecycleGeneration = event.lifecycleGeneration;
  }
  return admitted;
}
function reduceAgentEvent(state, event, dependencies, options = {}) {
  if (!eventMatchesTranscriptSession(state, event)) return "ignored-session";
  const previousTurn = state.activeTurn;
  const admission = classifyAgentEvent({
    selected: state,
    activeRun: previousTurn,
    event,
    terminalRun: Boolean(state.recentRuns.get(event.runId)?.terminalStatus)
  });
  if (admission === "ignored-session") return "ignored-session";
  const lateStartTool = event.stream === "tool" && event.data.phase === "start" && event.deliveryEvent === "agent" && options.allowSequenceBackfill !== true && options.replaySnapshot !== true && previousTurn?.runId === event.runId && admission !== "ignored-run" && admission !== "ignored-terminal" ? previousTurn.toolById.get(itemToolCallId(event.data) ?? "") : void 0;
  if (lateStartTool && lateStartTool.status !== "running" && lateStartTool.agentSequenceUnconfirmed !== true && event.agentSeq < lateStartTool.firstSeq) {
    confirmRecoveredToolSequence(previousTurn, lateStartTool, event.agentSeq, event.timestamp);
    state.revision += 1;
    return "applied";
  }
  const isSequenceBackfill = admission === "ignored-sequence";
  if (isSequenceBackfill && (!options.allowSequenceBackfill || !previousTurn || !acceptsBackfillSequence(previousTurn, event))) {
    return "ignored-sequence";
  }
  if (admission === "ignored-run" || admission === "ignored-terminal") return "ignored-run";
  if (previousTurn?.runId === event.runId && !acceptsBackfillSequence(previousTurn, event)) {
    if (!options.replaySnapshot) {
      previousTurn.lastAgentSeq = Math.max(previousTurn.lastAgentSeq, event.agentSeq);
    }
    return "ignored-sequence";
  }
  const turn = admitTurn(state, event, dependencies, isSequenceBackfill);
  if (!turn) return "ignored-run";
  if (turn.sessionId && event.sessionId && turn.sessionId !== event.sessionId) {
    return "ignored-session";
  }
  if (turn.lifecycleGeneration && event.lifecycleGeneration && turn.lifecycleGeneration !== event.lifecycleGeneration) {
    return "ignored-run";
  }
  const insertBySequence = options.replaySnapshot === true || isSequenceBackfill || event.agentSeq <= (turn.lastSnapshotAgentSeq ?? -1);
  if (event.stream === "thinking") {
    reduceThinking(turn, event, dependencies, insertBySequence);
  } else if (event.stream === "assistant") {
    const observation = readTerminalGuardObservation(event.data);
    if (observation?.action === "commit" || observation?.action === "rollback") {
      applyTerminalGuardObservationDecision(turn, observation);
    } else {
      const content = reduceContent(turn, event, dependencies, insertBySequence);
      if (content && observation?.action === "update") {
        content.terminalGuardObservationToken = observation.token;
      }
    }
  } else if (event.stream === "tool") {
    reduceTool(turn, event, dependencies, insertBySequence);
  } else if (event.stream === "item" && readPreambleText(event.data) !== null) {
    reducePreamble(turn, event, dependencies);
  } else if (event.stream === "lifecycle" || event.stream === "item" || event.stream === "compaction") {
    if (event.stream === "item") {
      const recoveredTool = turn.toolById.get(itemToolCallId(event.data) ?? "");
      if (recoveredTool?.agentSequencePending === true) {
        confirmRecoveredToolSequence(turn, recoveredTool, event.agentSeq, event.timestamp);
        recoveredTool.lastSeq = Math.max(recoveredTool.lastSeq, event.agentSeq);
      }
    }
  }
  recordActivitySequence(turn, event);
  if (options.replaySnapshot) {
    turn.lastSnapshotAgentSeq = Math.max(turn.lastSnapshotAgentSeq ?? -1, event.agentSeq);
  } else {
    turn.lastAgentSeq = Math.max(turn.lastAgentSeq, event.agentSeq);
  }
  if (insertBySequence || snapshotSegmentFirstSeq(event) !== null) {
    finishTextBeforeKnownBoundaries(turn);
  }
  state.revision += 1;
  return "applied";
}
function extractMessageText(message) {
  if (typeof message === "string") return message;
  if (!message || typeof message !== "object" || Array.isArray(message)) return "";
  const record = message;
  if (typeof record.text === "string") return record.text;
  if (typeof record.content === "string") return record.content;
  if (!Array.isArray(record.content)) return "";
  return record.content.map((block) => {
    if (!block || typeof block !== "object" || Array.isArray(block)) return "";
    const value = block;
    return typeof value.text === "string" ? value.text : "";
  }).join("");
}
function finishTurnItems(turn, status, now) {
  for (const item of turn.items) {
    if (item.type === "thinking" && item.status === "running") {
      item.status = status === "final" ? "completed" : "interrupted";
      item.updatedAt = now;
    } else if (item.type === "tool" && item.status === "running") {
      if (status === "final" && isSessionsYieldTool(item.name) && !hasToolResultPayload(item)) {
        continue;
      }
      item.status = status === "error" ? "failed" : status === "final" ? "completed" : "cancelled";
      item.updatedAt = now;
    } else if (item.type === "content" && item.status === "streaming") {
      item.status = status === "final" ? "completed" : "interrupted";
      item.updatedAt = now;
    }
  }
}
function reduceChatEvent(state, event, dependencies) {
  const admission = classifyChatEvent({
    selected: state,
    activeRun: state.activeTurn,
    event
  });
  if (admission === "ignored-session") return "ignored-session";
  let turn = state.activeTurn;
  if (admission === "start-run" && event.runId) {
    turn = beginAssistantTurn(
      state,
      {
        runId: event.runId,
        sessionId: event.sessionId,
        lifecycleGeneration: event.lifecycleGeneration
      },
      dependencies
    );
  }
  if (!turn) return "ignored-run";
  if (admission === "bind-provisional-run" && event.runId) {
    if (!bindAssistantTurnRunId(state, turn.runId, event.runId)) return "ignored-run";
    turn = state.activeTurn;
  }
  if (admission === "ignored-run") return "ignored-run";
  if (!turn) return "ignored-run";
  if (event.sessionId && turn.sessionId && event.sessionId !== turn.sessionId) {
    return "ignored-session";
  }
  if (event.lifecycleGeneration && turn.lifecycleGeneration && event.lifecycleGeneration !== turn.lifecycleGeneration) {
    return "ignored-run";
  }
  if (event.state === "delta") {
    const messageText2 = event.message !== void 0 ? extractMessageText(event.message) : null;
    const synthetic = {
      runId: turn.runId,
      sessionKey: state.sessionKey,
      sessionId: event.sessionId,
      lifecycleGeneration: event.lifecycleGeneration,
      agentId: null,
      spawnedBy: null,
      agentSeq: turn.lastAgentSeq + 1,
      frameSeq: event.frameSeq,
      deliveryEvent: "agent",
      stream: "assistant",
      timestamp: dependencies.now(),
      data: {
        ...event.deltaText !== void 0 ? { delta: event.deltaText } : {},
        ...messageText2 !== null ? { text: stripCompletedContentSegments(turn, messageText2) } : {},
        replace: event.replace
      }
    };
    reduceContent(turn, synthetic, dependencies);
    state.revision += 1;
    return "applied";
  }
  const now = dependencies.now();
  const finalText = extractMessageText(event.message);
  if (finalText && event.state === "final") {
    const currentSegmentText = stripCompletedContentSegments(turn, finalText);
    const tail = activeAgentTail(turn);
    if (tail?.type === "content" && currentSegmentText) {
      tail.text = updateSnapshot(tail.text, currentSegmentText, true);
      tail.updatedAt = now;
    } else if (currentSegmentText) {
      appendAgentItem(turn, {
        id: dependencies.createId("content"),
        runId: turn.runId,
        firstSeq: turn.lastAgentSeq,
        lastSeq: turn.lastAgentSeq,
        startedAt: now,
        updatedAt: now,
        type: "content",
        status: "completed",
        text: currentSegmentText,
        sourceMode: "replaceable"
      });
    }
  }
  turn.status = event.state;
  turn.endedAt = now;
  finishTurnItems(turn, event.state, now);
  if (event.state === "aborted" || event.state === "error") {
    const message = event.errorMessage?.trim() || (event.state === "aborted" ? "The run was interrupted." : "The run failed.");
    const terminal = {
      id: dependencies.createId("terminal"),
      runId: turn.runId,
      firstSeq: turn.lastAgentSeq,
      lastSeq: turn.lastAgentSeq,
      startedAt: now,
      updatedAt: now,
      type: "terminal",
      status: event.state,
      message
    };
    turn.items.push(terminal);
  }
  state.recentRuns.set(turn.runId, {
    runId: turn.runId,
    sessionId: turn.sessionId,
    lifecycleGeneration: turn.lifecycleGeneration,
    lastAgentSeq: turn.lastAgentSeq,
    terminalStatus: event.state,
    expiresAt: now + RECENT_RUN_RETENTION_MS
  });
  pruneRecentRuns(state, now);
  state.revision += 1;
  return "applied";
}

// src/shared/browser/browserRecording.ts
var RecordingAction = {
  Click: "click",
  DoubleClick: "doubleClick",
  Input: "input",
  Select: "select",
  Key: "key",
  Scroll: "scroll",
  Navigate: "navigate",
  SwitchTab: "switchTab",
  OpenTab: "openTab",
  CloseTab: "closeTab",
  Gap: "gap",
  ContextMenu: "contextMenu",
  Drag: "drag",
  Hover: "hover",
  Observe: "observe"
};
var RECORDING_LIMITS = {
  steps: 200,
  durationMs: 30 * 6e4,
  screenshots: 12,
  imageBytes: 10 * 1024 * 1024,
  textLength: 64e3,
  imageEdge: 1280
};
var guestActions = /* @__PURE__ */ new Set([
  RecordingAction.Click,
  RecordingAction.DoubleClick,
  RecordingAction.Input,
  RecordingAction.Select,
  RecordingAction.Key,
  RecordingAction.Scroll,
  RecordingAction.ContextMenu,
  RecordingAction.Drag,
  RecordingAction.Hover,
  RecordingAction.Observe
]);

// src/renderer/libs/openclaw-chat/pipeline/heartbeat-display.ts
var HEARTBEAT_TOKEN = "HEARTBEAT_OK";
var DEFAULT_HEARTBEAT_ACK_MAX_CHARS = 300;
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function stripHeartbeatTokenForDisplay(raw, maxAckChars = DEFAULT_HEARTBEAT_ACK_MAX_CHARS) {
  let text = raw.trim();
  if (!text) return { shouldSkip: true };
  const strippedMarkup = text.replace(/<[^>]*>/g, " ").replace(/&nbsp;/gi, " ").replace(/^[*`~_]+/, "").replace(/[*`~_]+$/, "");
  if (!text.includes(HEARTBEAT_TOKEN) && !strippedMarkup.includes(HEARTBEAT_TOKEN)) {
    return { shouldSkip: false };
  }
  const tokenAtEnd = new RegExp(`${escapeRegExp(HEARTBEAT_TOKEN)}[^\\w]{0,4}$`);
  let changed = true;
  let didStrip = false;
  text = strippedMarkup.trim();
  while (changed) {
    changed = false;
    const next = text.trim();
    if (next.startsWith(HEARTBEAT_TOKEN)) {
      text = next.slice(HEARTBEAT_TOKEN.length).trimStart();
      didStrip = true;
      changed = true;
      continue;
    }
    if (tokenAtEnd.test(next)) {
      const index = next.lastIndexOf(HEARTBEAT_TOKEN);
      const before = next.slice(0, index).trimEnd();
      const after = next.slice(index + HEARTBEAT_TOKEN.length).trimStart();
      text = before ? `${before}${after}`.trimEnd() : "";
      didStrip = true;
      changed = true;
    }
  }
  if (!didStrip) return { shouldSkip: false };
  return { shouldSkip: !text || text.length <= maxAckChars };
}

// src/renderer/libs/openclaw-chat/pipeline/history-display-normalizer.ts
var SILENT_REPLY_PATTERN = /^\s*NO_REPLY\s*$/;
var FAILED_RUN_RETENTION_MS = 30 * 24 * 60 * 60 * 1e3;
var INTERRUPTED_MESSAGE_RETENTION_MS = 30 * 24 * 60 * 60 * 1e3;
function stripSilentReplySuffixFromText(text) {
  if (SILENT_REPLY_PATTERN.test(text.trim())) return text;
  return text.replace(/\s*NO_REPLY\s*$/i, "").trimEnd();
}

// src/renderer/libs/openclaw-chat/gateway/chat-history-protocol.ts
var HISTORY_MESSAGE_CHUNK_CHARS = 512 * 1024;
var asRecord3 = (value) => value !== null && typeof value === "object" && !Array.isArray(value) ? value : null;
var isTruncatedHistoryMessage = (message) => {
  const metadata = asRecord3(asRecord3(message)?.__openclaw);
  return metadata?.truncated === true;
};

// src/renderer/libs/openclaw-chat/model/browser-extension-display.ts
var GENERIC_FAILURE = "The agent run failed before producing a reply.";
function hidden(text) {
  const trimmed = text.trim();
  return Boolean(trimmed) && ("NO_REPLY".startsWith(trimmed.toUpperCase()) || trimmed === GENERIC_FAILURE || stripHeartbeatTokenForDisplay(trimmed).shouldSkip);
}
function stripSuffix(text) {
  return /NO_REPLY\s*$/i.test(text) ? stripSilentReplySuffixFromText(text) : text;
}
function messageText(message) {
  if (typeof message === "string") return message;
  if (!message || typeof message !== "object") return "";
  const value = message;
  if (typeof value.text === "string") return value.text;
  if (typeof value.content === "string") return value.content;
  if (!Array.isArray(value.content)) return "";
  return value.content.map((block) => {
    if (!block || typeof block !== "object") return "";
    return typeof block.text === "string" ? block.text : "";
  }).join("");
}
function prepareBrowserExtensionStreamEvent(value) {
  if (value.kind === "agent") {
    if (value.event.stream !== "assistant") return value;
    const data = value.event.data;
    const text2 = typeof data.text === "string" && data.text.trim() ? data.text : typeof data.delta === "string" ? data.delta : "";
    if (hidden(text2)) return null;
    return {
      ...value,
      event: {
        ...value.event,
        data: {
          ...data,
          ...typeof data.text === "string" ? { text: stripSuffix(data.text) } : {},
          ...typeof data.delta === "string" ? { delta: stripSuffix(data.delta) } : {}
        }
      }
    };
  }
  const event = value.event;
  if (event.state !== "delta" && event.state !== "final") return value;
  const text = messageText(event.message) || event.deltaText || "";
  if (hidden(text) || event.state === "final" && isTruncatedHistoryMessage(event.message)) {
    return event.state === "delta" ? null : {
      ...value,
      event: { ...event, message: void 0, deltaText: void 0 }
    };
  }
  const stripped = stripSuffix(text);
  if (stripped === text) return value;
  return {
    ...value,
    event: {
      ...event,
      ...event.message !== void 0 ? { message: { content: stripped } } : {},
      ...event.deltaText !== void 0 ? { deltaText: stripSuffix(event.deltaText) } : {}
    }
  };
}

// src/renderer/libs/openclaw-chat/model/browser-extension-stream.ts
function projectItem(item) {
  if (item.type === "content") return { id: item.id, type: "agentMessage", text: item.text };
  if (item.type === "thinking")
    return { id: item.id, type: "reasoning", content: [item.text], status: item.status };
  if (item.type === "terminal") return { id: item.id, type: "systemMessage", text: item.message };
  return {
    id: item.id,
    type: "toolCall",
    toolUseId: item.toolCallId,
    toolName: item.name,
    input: item.input,
    output: item.error ?? item.output,
    status: item.status === "running" ? "inProgress" : item.status,
    isError: item.status === "failed"
  };
}
function itemText(item) {
  return item.type === "reasoning" ? [
    ...Array.isArray(item.summary) ? item.summary : [],
    ...Array.isArray(item.content) ? item.content : []
  ].join("\n") : typeof item.text === "string" ? item.text : "";
}
function sameItem(history, live) {
  if (history.type !== live.type) return false;
  if (live.type === "toolCall")
    return Boolean(live.toolUseId) && history.toolUseId === live.toolUseId;
  const a = itemText(history).trim();
  const b = itemText(live).trim();
  return Boolean(a && b) && (a.startsWith(b) || b.startsWith(a));
}
function mergeItem(history, live) {
  if (live.type !== "toolCall") {
    return itemText(history).startsWith(itemText(live)) ? { ...history, status: live.status } : live;
  }
  const merged = {
    ...history,
    ...Object.fromEntries(Object.entries(live).filter(([, value]) => value !== void 0))
  };
  if (history.status !== "inProgress" && live.status === "inProgress") {
    merged.status = history.status;
    merged.output = history.output;
    merged.isError = history.isError;
  }
  return merged;
}
function reconcileItems(history, live) {
  const toolIndex = (item) => item.type === "toolCall" ? history.findIndex((candidate) => sameItem(candidate, item)) : -1;
  const matches = [];
  let previousMatch = -1;
  let unanchoredTool = false;
  for (let index = 0; index < live.length; index += 1) {
    const item = live[index];
    let match = toolIndex(item);
    if (item.type !== "toolCall" && !unanchoredTool) {
      const followingTool = live.slice(index + 1).map(toolIndex).find((value) => value >= 0);
      const end = followingTool ?? history.length;
      let boundary = end - 1;
      while (boundary >= 0 && history[boundary].type !== "toolCall") boundary -= 1;
      const start = Math.max(previousMatch + 1, boundary + 1);
      match = history.findIndex(
        (candidate, position) => position >= start && position < end && sameItem(candidate, item)
      );
    }
    if (match <= previousMatch) match = -1;
    if (item.type === "toolCall") unanchoredTool = match < 0;
    matches.push(match);
    if (match >= 0) previousMatch = match;
  }
  const items = [];
  let cursor = 0;
  for (let index = 0; index < live.length; index += 1) {
    const match = matches[index];
    if (match >= 0) {
      items.push(...history.slice(cursor, match), mergeItem(history[match], live[index]));
      cursor = match + 1;
    } else {
      const followingMatch = matches.slice(index + 1).find((value) => value >= 0);
      const position = followingMatch ?? history.length;
      items.push(...history.slice(cursor, position), live[index]);
      cursor = position;
    }
  }
  items.push(...history.slice(cursor));
  return { items, matches };
}
var BrowserExtensionStream = class {
  constructor(threadId) {
    this.threadId = threadId;
    this.history = { id: threadId, turns: [] };
  }
  threadId;
  history;
  state = createChatTranscriptState();
  nextId = 0;
  agentTextRun = null;
  anchor = null;
  completedRuns = /* @__PURE__ */ new Set();
  settled = false;
  beforeStart = null;
  displayTurnIds = /* @__PURE__ */ new Map();
  dependencies = {
    now: () => Date.now(),
    createId: (prefix) => `live-${prefix}-${++this.nextId}`
  };
  start(message, rawMessage) {
    this.finish();
    this.beforeStart = this.history;
    this.anchor = this.history.turns.length;
    const turnId = `pending-${this.nextId++}`;
    this.displayTurnIds.set(this.anchor, turnId);
    this.history = {
      ...this.history,
      turns: [
        ...this.history.turns,
        {
          id: turnId,
          items: [
            {
              type: "userMessage",
              content: [{ type: "text", text: message }],
              ...rawMessage ? { rawMessage } : {}
            }
          ]
        }
      ]
    };
  }
  setHistory(thread, authoritative = false) {
    if (thread.id !== this.threadId) return;
    if (this.anchor !== null && thread.turns.length <= this.anchor) {
      if (!authoritative) return;
      const displayId = this.displayTurnIds.get(this.anchor);
      this.displayTurnIds.clear();
      this.anchor = Math.max(0, thread.turns.length - 1);
      if (displayId && thread.turns.length) this.displayTurnIds.set(this.anchor, displayId);
    }
    this.history = {
      ...thread,
      turns: thread.turns.map((turn, index) => ({
        ...turn,
        id: this.displayTurnIds.get(index) ?? turn.id
      }))
    };
    this.beforeStart = null;
    if (this.settled) this.finish(true);
  }
  cancelStart() {
    const original = this.beforeStart;
    if (original && this.anchor !== null) this.displayTurnIds.delete(this.anchor);
    this.finish();
    if (original) this.history = original;
  }
  accept(value) {
    const prepared = prepareBrowserExtensionStreamEvent(value);
    if (!prepared) return false;
    value = prepared;
    const event = value.event;
    if (!event.sessionKey || event.runId && this.completedRuns.has(event.runId)) return false;
    if (!this.state.sessionKey) this.state.sessionKey = event.sessionKey;
    if (value.kind === "chat" && value.event.state === "delta" && this.agentTextRun === event.runId)
      return false;
    if (value.kind === "chat" && value.event.state === "error") return false;
    const result = value.kind === "agent" ? reduceAgentEvent(this.state, value.event, this.dependencies, {
      allowSequenceBackfill: value.event.deliveryEvent === "session.tool" || Number.isSafeInteger(value.event.data.progressSegmentFirstSeq)
    }) : reduceChatEvent(this.state, value.event, this.dependencies);
    if (result !== "applied") return false;
    if (value.kind === "agent" && value.event.stream === "assistant") {
      this.agentTextRun = readTerminalGuardObservation(value.event.data)?.action === "rollback" ? null : event.runId;
    }
    return true;
  }
  project() {
    const turn = this.state.activeTurn;
    if (!turn?.items.length) return this.history;
    const turns = this.history.turns.slice();
    const index = this.anchor ?? Math.max(0, turns.length - 1);
    const historical = turns[index] ?? { id: turn.id, items: [] };
    const live = turn.items.map(projectItem);
    turns[index] = { ...historical, items: reconcileItems(historical.items, live).items };
    return { ...this.history, turns };
  }
  finish(preserveUnpersisted = false) {
    if (this.state.activeTurn) {
      this.completedRuns.add(this.state.activeTurn.runId);
      if (this.completedRuns.size > 24)
        this.completedRuns.delete(this.completedRuns.values().next().value);
    }
    if (preserveUnpersisted && this.state.activeTurn?.items.length) {
      const historical = this.history.turns[this.anchor ?? Math.max(0, this.history.turns.length - 1)]?.items ?? [];
      const live = this.state.activeTurn.items.filter((item) => item.type !== "terminal").map(projectItem);
      const { matches } = reconcileItems(historical, live);
      const covered = live.every((item, index) => {
        const candidate = historical[matches[index]];
        if (!candidate) return false;
        if (!sameItem(candidate, item)) return false;
        return item.type === "toolCall" ? candidate.status !== "inProgress" && Boolean(candidate.output || !item.output) : itemText(candidate).includes(itemText(item));
      });
      if (!covered) {
        this.settled = true;
        for (const item of this.state.activeTurn.items) {
          if (item.type === "tool" && item.status === "running") item.status = "interrupted";
          if (item.type === "thinking" && item.status === "running") item.status = "interrupted";
          if (item.type === "content" && item.status === "streaming") item.status = "interrupted";
        }
        return;
      }
    }
    this.state = createChatTranscriptState();
    this.agentTextRun = null;
    this.anchor = null;
    this.settled = false;
    this.beforeStart = null;
  }
};
export {
  BrowserExtensionStream
};
