export const scenarioLabels = {
  zh: {
    rendererLoading: '界面正在加载…',
    rendererUnavailable: '此交互界面暂时不可用，请重新加载或重新生成。',
    eyebrow: '投入与交付测算',
    intro: '调整投入，看看交付周期和预算如何变化。',
    lean: '精简团队',
    balanced: '均衡方案',
    fast: '加速交付',
    team: '团队人数',
    focus: '每日专注时间',
    people: '人',
    hours: '小时',
    days: '工作日',
    cost: '预计成本',
    dailyRate: '每人每工作日成本',
    duration: '交付周期',
    capacity: '每日有效产能',
    progress: '累计交付预测',
    effort: '工作量',
    timeline: '周期',
    comparison: '方案对比',
    plan: '方案',
    budget: '预算',
    deadline: '目标周期',
    within: '在目标范围内',
    beyond: '超过目标',
    tasks: '示例工作拆分',
    follow: '继续分析这个方案',
    unavailable: '此宿主未启用后续消息',
    assumption:
      '演示公式：工作量 ÷ 有效产能；82% 基础利用率，每增加一人折减 2.5% 协作效率。成本按工作日计。不含假期和依赖阻塞。',
    draft: '请继续分析当前方案：',
    chartLabel: '累计交付比例',
    selected: '当前选择',
  },
  en: {
    rendererLoading: 'Loading interactive content…',
    rendererUnavailable: 'Interactive content is unavailable. Reload it or request a new version.',
    eyebrow: 'Delivery & investment',
    intro: 'Adjust the inputs and explore delivery time and cost.',
    lean: 'Lean team',
    balanced: 'Balanced',
    fast: 'Accelerated',
    team: 'Team size',
    focus: 'Daily focus time',
    people: 'people',
    hours: 'hours',
    days: 'workdays',
    cost: 'Estimated cost',
    dailyRate: 'Cost per person per workday',
    duration: 'Delivery time',
    capacity: 'Daily effective capacity',
    progress: 'Cumulative delivery forecast',
    effort: 'Workload',
    timeline: 'Duration',
    comparison: 'Compare plans',
    plan: 'Plan',
    budget: 'Budget',
    deadline: 'Target duration',
    within: 'Within target',
    beyond: 'Over target',
    tasks: 'Sample work breakdown',
    follow: 'Explore this plan',
    unavailable: 'Follow-up messages unavailable in this host',
    assumption:
      'Demo model: workload ÷ effective capacity; 82% baseline utilization, minus 2.5% coordination efficiency per additional person. Cost uses workdays. Holidays and blocked dependencies are excluded.',
    draft: 'Please analyze the selected plan:',
    chartLabel: 'Cumulative delivery percentage',
    selected: 'Current selection',
  },
};
